import warnings

# Suppress urllib3 v2 NotOpenSSLWarning on macOS LibreSSL environments
warnings.filterwarnings("ignore", message=r".*urllib3 v2 only supports OpenSSL 1\.1\.1\+.*")
try:
    import urllib3
    warnings.filterwarnings("ignore", category=urllib3.exceptions.NotOpenSSLWarning)
except Exception:
    pass

import argparse
import json
from pathlib import Path
import mlx.core as mx
import mlx.nn as nn
import mlx.optimizers as optim
import numpy as np
import pandas as pd
import yfinance as yf

from stock_llama import StockPredictionModel, LlamaWrapperConfig

# Leading High-Tech & Semiconductor/Software/Internet Stocks
TECH_TICKERS = [
    "AAPL", "MSFT", "NVDA", "GOOGL", "AMZN", "META", "TSLA", "AVGO", "ORCL", "ADBE",
    "CRM", "AMD", "QCOM", "INTC", "CSCO", "TXN", "INTU", "NOW", "AMAT", "MU",
    "LRCX", "ADI", "PANW", "SNPS", "CDNS", "KLAC", "CRWD", "PLTR", "MRVL", "ANET"
]

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)

WEIGHTS_FILE = str(DATA_DIR / "tech_stock_model.safetensors")
STATS_FILE = str(DATA_DIR / "normalization_tech_stats.json")


# 1. Model architecture is the Llama transformer wrapper in stock_llama.py.


# 2. Historical Feature Engineering Function
def compute_technical_features(df: pd.DataFrame) -> pd.DataFrame:
    """Computes technical indicators (RSI, MACD, Volume Trend, Daily Return)

    and next trading day return label.
    """
    df = df.copy()

    # Feature 1: 14-Period RSI
    delta = df['Close'].diff()
    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)
    avg_gain = gain.rolling(window=14).mean()
    avg_loss = loss.rolling(window=14).mean()
    rs = avg_gain / (avg_loss + 1e-9)
    df['RSI'] = 100 - (100 / (1 + rs))

    # Feature 2: MACD (12-period EMA - 26-period EMA)
    ema12 = df['Close'].ewm(span=12, adjust=False).mean()
    ema26 = df['Close'].ewm(span=26, adjust=False).mean()
    df['MACD'] = ema12 - ema26

    # Feature 3: Volume Trend (Current Volume / 20-day Rolling Average)
    df['Volume_Trend'] = df['Volume'] / df['Volume'].rolling(window=20).mean()

    # Feature 4: Past Daily Return (%)
    df['Daily_Return'] = df['Close'].pct_change() * 100

    # Target Label: Next Trading Day Return (%)
    # Next day's price gain: (Close_{t+1} - Close_t) / Close_t * 100
    df['Next_Day_Return'] = (df['Close'].shift(-1) - df['Close']) / df['Close'] * 100
    # Binary classification target: 1 if next day closes positive, 0 otherwise
    df['Target'] = (df['Next_Day_Return'] > 0.0).astype(float)

    return df


# 3. Retrieve Historical Tech Stock Data & Build Training Dataset
def build_historical_dataset(tickers=None, period="2y", train_split=0.85):
    """Retrieves historical data for high tech tickers and constructs

    normalized feature matrices and labels for training and validation.
    """
    if tickers is None:
        tickers = TECH_TICKERS
    all_features = []
    all_targets = []

    print("=" * 65)
    print(f"📥 Retrieving {period} historical data for {len(tickers)} High-Tech stocks...")
    print("=" * 65)

    successful_tickers = 0
    for ticker in tickers:
        try:
            stock = yf.Ticker(ticker)
            df = stock.history(period=period)
            if df.empty or len(df) < 50:
                print(f"  ⚠️ Skipping {ticker}: Insufficient historical data ({len(df)} rows)")
                continue

            processed_df = compute_technical_features(df)
            # Drop NaN rows generated by rolling windows and the final row without next-day return
            valid_df = processed_df[['RSI', 'MACD', 'Volume_Trend', 'Daily_Return', 'Target']].dropna()

            if len(valid_df) > 0:
                features = valid_df[['RSI', 'MACD', 'Volume_Trend', 'Daily_Return']].values
                targets = valid_df['Target'].values

                all_features.append(features)
                all_targets.append(targets)
                successful_tickers += 1
                ticker_str = str(ticker)
                print(f"  ✓ {ticker_str:<5} loaded: {len(valid_df)} historical samples")
        except Exception as e:
            print(f"  ❌ Error fetching {ticker}: {e}")

    if not all_features:
        raise RuntimeError("No historical data could be retrieved for Tech tickers.")

    X = np.vstack(all_features).astype(np.float32)
    y = np.concatenate(all_targets).astype(np.float32).reshape(-1, 1)

    print("-" * 65)
    print(f"Total dataset size: {X.shape[0]} samples across {successful_tickers} stocks")

    # Train/Validation temporal or random split with reproducibility
    num_samples = X.shape[0]
    indices = np.random.RandomState(42).permutation(num_samples)
    split_idx = int(num_samples * train_split)

    train_idx, val_idx = indices[:split_idx], indices[split_idx:]
    X_train_raw, y_train = X[train_idx], y[train_idx]
    X_val_raw, y_val = X[val_idx], y[val_idx]

    # Calculate normalization parameters strictly on the training partition
    norm_mean = np.mean(X_train_raw, axis=0)
    norm_std = np.std(X_train_raw, axis=0) + 1e-9

    X_train = (X_train_raw - norm_mean) / norm_std
    X_val = (X_val_raw - norm_mean) / norm_std

    # Save normalization statistics for inference
    stats = {
        "mean": norm_mean.tolist(),
        "std": norm_std.tolist(),
        "features": ['RSI', 'MACD', 'Volume_Trend', 'Daily_Return']
    }
    with open(STATS_FILE, "w") as f:
        json.dump(stats, f, indent=2)

    print(f"Training samples:   {len(X_train)}")
    print(f"Validation samples: {len(X_val)}")
    print(f"Saved normalization stats to '{STATS_FILE}'")
    print("=" * 65)

    return X_train, y_train, X_val, y_val, norm_mean, norm_std


# 4. Train Model with MLX
def train_model(model, X_train, y_train, X_val, y_val, epochs=60, batch_size=64, lr=1e-3):
    """Trains the StockPredictionModel using Apple MLX."""
    print("\n🧠 Training MLX Llama Transformer for Tech Stocks...")
    print("   Architecture: transformer wrapper (feature tokens -> Llama decoder -> pooled logit)")
    print(f"   Epochs: {epochs} | Batch Size: {batch_size} | Learning Rate: {lr}\n")

    optimizer = optim.Adam(learning_rate=lr)

    def loss_fn(model, x, y):
        logits = model(x)
        return nn.losses.binary_cross_entropy(logits, y)

    loss_and_grad_fn = nn.value_and_grad(model, loss_fn)

    X_val_mx = mx.array(X_val)
    y_val_mx = mx.array(y_val)

    num_samples = X_train.shape[0]

    for epoch in range(1, epochs + 1):
        # Shuffle training batches
        perm = np.random.permutation(num_samples)
        epoch_losses = []

        for start_idx in range(0, num_samples, batch_size):
            batch_indices = perm[start_idx:start_idx + batch_size]
            batch_x = mx.array(X_train[batch_indices])
            batch_y = mx.array(y_train[batch_indices])

            loss, grads = loss_and_grad_fn(model, batch_x, batch_y)
            optimizer.update(model, grads)
            mx.eval(model.parameters(), optimizer.state)
            epoch_losses.append(loss.item())

        train_loss = float(np.mean(epoch_losses))

        # Validation evaluation
        if epoch % 10 == 0 or epoch == epochs:
            val_logits = model(X_val_mx)
            val_loss = float(nn.losses.binary_cross_entropy(val_logits, y_val_mx).item())
            val_probs = mx.sigmoid(val_logits)
            val_preds = (val_probs >= 0.5).astype(mx.float32)
            val_acc = float(mx.mean((val_preds == y_val_mx).astype(mx.float32)).item() * 100)

            print(f"  Epoch [{epoch:>2}/{epochs:>2}] | "
                  f"Train Loss: {train_loss:.4f} | "
                  f"Val Loss: {val_loss:.4f} | "
                  f"Val Accuracy: {val_acc:.2f}%")

    # Save trained weights
    model.save_weights(WEIGHTS_FILE)
    print(f"\n💾 Model weights successfully saved to '{WEIGHTS_FILE}'")


# 5. Live Tech Stock Inference & Next Opening Day Forecast
def predict_best_stocks_for_next_open(model, norm_mean, norm_std, tickers=None, threshold=75.0):
    """Fetches live market features for tech stocks, normalizes using training stats,

    and generates ranked buy signals for the next opening trading day.
    """
    if tickers is None:
        tickers = TECH_TICKERS
    print("\n" + "=" * 65)
    print("🔮 Forecasting Top High-Tech Stocks for Next Opening Trading Day")
    print("=" * 65)

    results = []
    for ticker in tickers:
        try:
            stock = yf.Ticker(ticker)
            df = stock.history(period="60d")
            if df.empty or len(df) < 30:
                continue

            # Compute technical indicators
            delta = df['Close'].diff()
            gain = delta.clip(lower=0)
            loss = -delta.clip(upper=0)
            avg_gain = gain.rolling(window=14).mean()
            avg_loss = loss.rolling(window=14).mean()
            rs = avg_gain / (avg_loss + 1e-9)
            df['RSI'] = 100 - (100 / (1 + rs))

            ema12 = df['Close'].ewm(span=12, adjust=False).mean()
            ema26 = df['Close'].ewm(span=26, adjust=False).mean()
            df['MACD'] = ema12 - ema26

            df['Volume_Trend'] = df['Volume'] / df['Volume'].rolling(window=20).mean()
            df['Daily_Return'] = df['Close'].pct_change() * 100

            latest_features = df[['RSI', 'MACD', 'Volume_Trend', 'Daily_Return']].dropna().iloc[-1].values
            latest_price = df['Close'].iloc[-1]

            # Standardize using training dataset statistics
            norm_features = (latest_features - norm_mean) / norm_std
            input_tensor = mx.array(norm_features.reshape(1, -1).astype(np.float32))

            # Model inference
            raw_logits = model(input_tensor)
            probability = float(mx.sigmoid(raw_logits).item() * 100)

            # Assign trading signal based on probabilities
            if probability >= threshold:
                signal = "BUY 🚀"
            elif probability <= (100.0 - threshold):
                signal = "SELL 🔻"
            elif probability >= 55.0:
                signal = "BUY (Moderate) 📈"
            elif probability <= 45.0:
                signal = "SELL (Moderate) 📉"
            else:
                signal = "HOLD / SKIP ⏸️"
            results.append({
                "ticker": ticker,
                "price": float(latest_price),
                "probability": probability,
                "rsi": float(latest_features[0]),
                "macd": float(latest_features[1]),
                "volume_trend": float(latest_features[2]),
                "daily_return": float(latest_features[3]),
                "signal": signal
            })
        except Exception as e:
            print(f"  ❌ Error evaluating {ticker}: {e}")

    # Rank by probability descending
    results.sort(key=lambda x: x["probability"], reverse=True)

    print(f"{'Rank':<6}{'Ticker':<8}{'Price':<10}{'Confidence':<14}{'RSI':<8}{'MACD':<8}{'Signal':<15}")
    print("-" * 65)
    for rank, item in enumerate(results, start=1):
        print(f"{rank:<6}{item['ticker']:<8}${item['price']:<9.2f}{item['probability']:>6.2f}%       "
              f"{item['rsi']:<8.1f}{item['macd']:<8.2f}{item['signal']:<15}")

    print("=" * 65)
    best_stock = results[0] if results else None
    if best_stock:
        print(f"🏆 BEST TECH STOCK TO BUY FOR NEXT OPENING BELL: {best_stock['ticker']}")
        print(f"   Confidence Score:   {best_stock['probability']:.2f}%")
        print(f"   Current Price:      ${best_stock['price']:.2f}")
        print(f"   Signal:             {best_stock['signal']}")
        print(f"   Technical Profile:  RSI: {best_stock['rsi']:.1f} | MACD: {best_stock['macd']:.2f} | "
              f"Vol Trend: {best_stock['volume_trend']:.2f}x | Return: {best_stock['daily_return']:+.2f}%")

    # 1. Top 5 to BUY (highest probability)
    top_5_buy = results[:5]
    print("\n" + "-" * 65)
    print("🚀 TOP 5 TECH STOCKS TO BUY (Highest Bullish Confidence):")
    print(f"{'Rank':<6}{'Ticker':<8}{'Price':<10}{'Confidence':<14}{'Signal':<15}")
    print("-" * 65)
    for rank, item in enumerate(top_5_buy, start=1):
        print(f"{rank:<6}{item['ticker']:<8}${item['price']:<9.2f}{item['probability']:>6.2f}%       "
              f"{item['signal']:<15}")

    # 2. Top 5 to SELL (lowest probability / highest bearish momentum)
    top_5_sell = sorted(results, key=lambda x: x["probability"])[:5]
    print("\n" + "-" * 65)
    print("🔻 TOP 5 TECH STOCKS TO SELL (Lowest Probability / Bearish):")
    print(f"{'Rank':<6}{'Ticker':<8}{'Price':<10}{'Confidence':<14}{'Signal':<15}")
    print("-" * 65)
    for rank, item in enumerate(top_5_sell, start=1):
        print(f"{rank:<6}{item['ticker']:<8}${item['price']:<9.2f}{item['probability']:>6.2f}%       "
              f"{item['signal']:<15}")

    # 3. Top 5 to HOLD / SKIP (closest to neutral 50.0%)
    top_5_hold = sorted(results, key=lambda x: abs(x["probability"] - 50.0))[:5]
    print("\n" + "-" * 65)
    print("⏸️ TOP 5 TECH STOCKS TO HOLD / SKIP (Closest to Neutral 50% Momentum):")
    print(f"{'Rank':<6}{'Ticker':<8}{'Price':<10}{'Confidence':<14}{'Signal':<15}")
    print("-" * 65)
    for rank, item in enumerate(top_5_hold, start=1):
        print(f"{rank:<6}{item['ticker']:<8}${item['price']:<9.2f}{item['probability']:>6.2f}%       "
              f"{item['signal']:<15}")
    print("=" * 65)

    return results


# 6. Main Execution Pipeline
def main():
    parser = argparse.ArgumentParser(description="Retrieve historical High-Tech stock data, train MLX model, and predict top tech stock.")
    parser.add_argument("--period", type=str, default="2y", help="Historical data retrieval period (e.g. 1y, 2y, 5y)")
    parser.add_argument("--epochs", type=int, default=60, help="Number of training epochs")
    parser.add_argument("--batch-size", type=int, default=64, help="Training batch size")
    parser.add_argument("--lr", type=float, default=1e-3, help="Learning rate")
    parser.add_argument("--threshold", type=float, default=75.0, help="Confidence threshold percentage for buy signals")
    args = parser.parse_args()

    # Step 1: Retrieve historical data & prepare dataset
    X_train, y_train, X_val, y_val, norm_mean, norm_std = build_historical_dataset(
        tickers=TECH_TICKERS, period=args.period
    )

    # Step 2: Initialize model and train
    model = StockPredictionModel(LlamaWrapperConfig(input_dim=4))
    train_model(
        model=model,
        X_train=X_train,
        y_train=y_train,
        X_val=X_val,
        y_val=y_val,
        epochs=args.epochs,
        batch_size=args.batch_size,
        lr=args.lr
    )

    # Step 3: Run live forecasting for next opening trading day
    predict_best_stocks_for_next_open(
        model=model,
        norm_mean=norm_mean,
        norm_std=norm_std,
        tickers=TECH_TICKERS,
        threshold=args.threshold
    )


if __name__ == "__main__":
    main()
